(function() {var implementors = {};
implementors["jack"] = ["impl&lt;N, P&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"struct\" href=\"jack/client/struct.AsyncClient.html\" title=\"struct jack::client::AsyncClient\">AsyncClient</a>&lt;N, P&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;N: <a class=\"trait\" href=\"jack/client/trait.NotificationHandler.html\" title=\"trait jack::client::NotificationHandler\">NotificationHandler</a>,<br>&nbsp;&nbsp;&nbsp;&nbsp;P: <a class=\"trait\" href=\"jack/client/trait.ProcessHandler.html\" title=\"trait jack::client::ProcessHandler\">ProcessHandler</a>,&nbsp;</span>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"struct\" href=\"jack/client/struct.Client.html\" title=\"struct jack::client::Client\">Client</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"struct\" href=\"jack/ringbuffer/struct.RingBufferReader.html\" title=\"struct jack::ringbuffer::RingBufferReader\">RingBufferReader</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"struct\" href=\"jack/ringbuffer/struct.RingBufferWriter.html\" title=\"struct jack::ringbuffer::RingBufferWriter\">RingBufferWriter</a>","impl&lt;PS:&nbsp;<a class=\"trait\" href=\"jack/port/trait.PortSpec.html\" title=\"trait jack::port::PortSpec\">PortSpec</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"struct\" href=\"jack/port/struct.Port.html\" title=\"struct jack::port::Port\">Port</a>&lt;PS&gt;",];
implementors["libloading"] = ["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"struct\" href=\"libloading/os/unix/struct.Library.html\" title=\"struct libloading::os::unix::Library\">Library</a>","impl&lt;T:&nbsp;<a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"struct\" href=\"libloading/os/unix/struct.Symbol.html\" title=\"struct libloading::os::unix::Symbol\">Symbol</a>&lt;T&gt;","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"struct\" href=\"libloading/struct.Library.html\" title=\"struct libloading::Library\">Library</a>","impl&lt;'lib, T:&nbsp;<a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"struct\" href=\"libloading/struct.Symbol.html\" title=\"struct libloading::Symbol\">Symbol</a>&lt;'lib, T&gt;",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
